### PR TITLE
Group power function

### PR DESCRIPTION
**Pull request by matthewleon**
Addresses https://github.com/morganthomas/purescript-group/issues/9

### CODE REVIEW

**Comment by morganthomas** [comment]
This looks good to me! I don't see any issues with merging this.

**Comment by hdgarrood** [comment]
Could perhaps do the negative and equals-zero checks outside of the TCO'd `go`, so that we don't need to repeat those checks in every iteration once we start recursing?

**Comment by matthewleon** [comment]
Amended. Do people mind having another look?

**Comment by hdgarrood** [comment]
The implementation now looks good to me, but (sorry) I've just realised that the docs are perhaps a little confusing: for some type `R` with a `Semiring` instance, the multiplication function has type `R -> R -> R`, not `R -> Int -> R`. Therefore, `power` is only really the same as Semiring multiplication (i.e. `mul`) for `Additive Int`.

This function is closely related to the equivalence between modules over the ring Z (aka Z-modules) and abelian groups, in that every abelian group can be regarded as a Z-module by using this `power` function as *scalar* multiplication. However, scalar multiplication and semiring multiplication are different kinds of multiplication, and so if we want to use the word "multiplication" we should probably disambiguate.

**Comment by matthewleon** [comment]
@hdgarrood thanks! Amended.

**Review by hdgarrood — APPROVED** [review]
Looks good to me! There's a bit more that can be said about this function (cf. Z-modules) but I think there's maybe a decent argument to be made that the docs here aren't necessarily the right place for this. Alternatively the docs could always be expanded later too.

**Comment by morganthomas** [comment]
These changes look good to me!

**Comment by morganthomas** [comment]
Bumped version to 3.3.0.

**Pull request merged**
