### PR TITLE
v0.12.0 and psc-package support

### PR DESCRIPTION
**Pull request by adkelley**
If you like, I'll be happy to add this repository to the psc-package set once my changes have been merged.

### CODE REVIEW

**Comment by morganthomas** [comment]
Thank you for the contribution! I'm unfamiliar with psc-package (I don't do anything with PureScript beyond this package), but I trust that these changes are good.

**Comment by morganthomas** [comment]
I think it would be good to add this to the package set. Anything needed such as a tag created?

**Comment by adkelley** [comment]
Glad you agree.  No tag necessary.  Instructions for adding purescript-group to psc-package can be found here: https://github.com/purescript/psc-package  Let me know if would like to do it, or again I'll be happy to add it.

**Comment by morganthomas** [comment]
Thanks Alex! Please go ahead and add it. :-)

**Comment by adkelley** [comment]
Hi Morgan.  I believe, in order for Bower to pick up the 0.12 changes, that you need to add a new tag (4.0.0).  Cheers, Alex

**Comment by adkelley** [comment]
That did the trick, thank you!  I'll submit a pull request to psc-package as well.  Check your Travis settings though, it doesn't appear you've had a successful build yet.  

Cheers,
Alex

**Pull request merged**
