### PR TITLE
Add version badge to README

### PR DESCRIPTION
**Pull request by adkelley**
Besides this version badge, if you have a Travis account,  then you can add a travis.yml file to the root directory.  Subsequently, you can add a Travis badge to the README to show that the package is building properly.  Let me know if you need help with it.

Note, I use your package in one of my tutorials, so this is why I'm keen to get it properly supported under v0.12.

### CODE REVIEW

**Review by morganthomas — APPROVED** [review]

**Comment by morganthomas** [comment]
Thanks @adkelley ! Added travis, let's see if it works.

**Comment by morganthomas** [comment]
@adkelley I added the tag as well. Is it all set to be usable for your tutorial?

**Comment by adkelley** [comment]
One more step: If you look at your [releases](https://github.com/morganthomas/purescript-group/releases) page, it's still showing your latest release to be v2.1.0.  You need to create a new release, and assign it to your tag v4.0.0  Here's some [instructions](https://help.github.com/articles/creating-releases/) on how to do it.

**Comment by morganthomas** [comment]
Thanks @adkelley ! Sorry for the delay.

**Pull request merged**
