### PR TITLE
group -> semigroup in docs

### LINKED ISSUE #6: typo in Commutative docs?
"Instances must satisfy the following law in addition to the group laws:"

This should probably say "semigroup laws" rather than "group laws", no?

### PR DESCRIPTION
**Pull request by hrb90**
Fixes #6.

### CODE REVIEW

**Comment by hrb90** [comment]
Actually, since I can merge this I think I'll go ahead and do so :smile: but I think @morganthomas may need to bump the pursuit version?

**Comment by morganthomas** [comment]
@hrb90 I just bumped the version. I don't know whether you're able to do so. Feel free to try. https://pursuit.purescript.org/help/authors I will grant you the permissions needed if possible and needed.

**Comment by morganthomas** [comment]
Actually, I think the correction is incorrect. A commutative group, or an abelian group, is a group which satisfies the commutative law. Not all groups are commutative. Therefore I think the original wording was the correct wording. Would you care to check my reasoning, revert the change if you agree, and try bumping the version, @hrb90 ? Source: https://en.wikipedia.org/wiki/Group_(mathematics)#Definition Also @matthewleon, what do you think?

**Comment by matthewleon** [comment]
You can have a commutative semigroup that is not a group, though, if it lacks an inverse operation: https://www.wikiwand.com/en/Special_classes_of_semigroups

That seems to be what this TC is describing, as the superclass is `Semigroup,` not `Group`.

A datatype that is an instance of both this TC _and_ `Group` would then be an abelian. Whether you would want to create a new TC for that would be a separate issue.

Hope my own thinking here is clear :).

**Comment by hdgarrood** [comment]
Yes, I agree with @matthewleon. I think this is correct now, after merging. For example, the set of natural numbers together with the addition operation form a commutative semigroup (in fact a monoid) but not a group.

**Comment by hrb90** [comment]
Yes, I think @matthewleon and @hdgarrood pretty much covered it.

**Comment by morganthomas** [comment]
Ah, I see it now. Commutative is a definition of a commutative semigroup, not a commutative group. We are all in agreement. Thanks everybody, rock on!

**Pull request merged**
